services:
  backend:
    volumes:
      - ./appdata/data:/app/data
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=backend
      - APP_DIR=/app
      - ENVIRONMENT=development
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

  predictor-eta:
    volumes:
      - ./appdata/models:/app/models
      - ./appdata/data:/app/data
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=predictor-eta
      - APP_DIR=/app
      - ENVIRONMENT=development
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload", "--log-level", "debug"]

  # predictor-fuel:
  #   volumes:
  #     - ./appdata/models:/app/models
  #     - ./appdata/data:/app/data
  #     - ./appdata/logs:/app/logs
  #     - ./thesis:/app/thesis
  #   environment:
  #     - SERVICE=predictor-fuel
  #     - APP_DIR=/app
  #     - ENVIRONMENT=development
  #   command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload", "--log-level", "debug"]

  # predictor-stops:
  #   volumes:
  #     - ./appdata/models:/app/models
  #     - ./appdata/data:/app/data
  #     - ./appdata/logs:/app/logs
  #     - ./thesis:/app/thesis
  #   environment:
  #     - SERVICE=predictor-stops
  #     - APP_DIR=/app
  #     - ENVIRONMENT=development
  #   command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--reload", "--log-level", "debug"]

  drift:
    volumes:
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=drift
      - APP_DIR=/app
      - ENVIRONMENT=development
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8004", "--reload", "--log-level", "debug"]

  frontend:
    volumes:
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=frontend
      - APP_DIR=/app
      - ENVIRONMENT=development
    command: ["uv", "run", "python", "main.py"]
