services:
  backend:
    volumes:
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=backend
      - APP_DIR=/app
      - ENVIRONMENT=development

  predictor-eta:
    volumes:
      - ./appdata/models:/app/models
      - ./appdata/common:/app/common:ro
      - ./appdata/data:/app/data:ro
      - ./appdata/logs:/app/logs
      - ./appdata/misc:/app/misc:ro
      - ./thesis:/app/thesis
    environment:
      - SERVICE=predictor-eta
      - APP_DIR=/app
      - ENVIRONMENT=development

  predictor-fuel:
    volumes:
      - ./appdata/models:/app/models
      - ./appdata/common:/app/common:ro
      - ./appdata/data:/app/data:ro
      - ./appdata/logs:/app/logs
      - ./appdata/misc:/app/misc:ro
      - ./thesis:/app/thesis
    environment:
      - SERVICE=predictor-fuel
      - APP_DIR=/app
      - ENVIRONMENT=development

  predictor-stops:
    volumes:
      - ./appdata/models:/app/models
      - ./appdata/common:/app/common:ro
      - ./appdata/data:/app/data:ro
      - ./appdata/logs:/app/logs
      - ./appdata/misc:/app/misc:ro
      - ./thesis:/app/thesis
    environment:
      - SERVICE=predictor-stops
      - APP_DIR=/app
      - ENVIRONMENT=development

  drift:
    volumes:
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=drift
      - APP_DIR=/app
      - ENVIRONMENT=development

  frontend:
    volumes:
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=frontend
      - APP_DIR=/app
      - ENVIRONMENT=development

  summarizer:
    volumes:
      - ./appdata/logs:/app/logs
      - ./thesis:/app/thesis
    environment:
      - SERVICE=summarizer
      - APP_DIR=/app
      - ENVIRONMENT=development
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
